# Generated by Django 2.0.1 on 2018-01-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinicaltrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('startDate', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('clinicaltrial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaltrials.clinicaltrial')),
            ],
        ),
    ]
