# Generated by Django 2.0.1 on 2018-01-19 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0002_remove_clinicaltrial_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
