# Generated by Django 2.0.1 on 2018-01-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0003_clinicaltrial_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.FileField(default='nullz file', upload_to=''),
            preserve_default=False,
        ),
    ]
