# Generated by Django 2.0.1 on 2018-01-19 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0004_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploadDate',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
