# Generated by Django 2.0.1 on 2018-01-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0005_file_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
