# Generated by Django 2.0.1 on 2018-01-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0006_auto_20180119_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
