# Generated by Django 2.0.1 on 2018-01-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0008_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='clinicaltrial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaltrials.clinicaltrial'),
        ),
    ]
