# Generated by Django 2.0.1 on 2018-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0011_auto_20180123_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='dataHash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
