# Generated by Django 2.0.1 on 2018-01-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0012_file_datahash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.AddField(
            model_name='file',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
