# Generated by Django 2.0.1 on 2018-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0013_auto_20180124_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
