# Generated by Django 2.0.1 on 2018-01-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0014_file_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
