# Generated by Django 2.0.1 on 2018-03-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0020_clinicaltrial_adverseevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='adverseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10000)),
                ('events', models.TextField(blank=True, null=True)),
                ('clinicaltrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaltrials.clinicaltrial')),
            ],
        ),
    ]
