# Generated by Django 2.0.1 on 2018-03-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0021_adverseevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='adverseEvents',
        ),
    ]
