# Generated by Django 2.0.1 on 2018-03-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaltrials', '0022_remove_clinicaltrial_adverseevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
    ]
